[package]
name = "gosee"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdns-sd = "0.6"
rocket = "0.5.0-rc.2"
tokio = "1.25"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
